### ISSUE TITLE
Invalid number of checks displayed

### ISSUE THREAD

**Issue by annfang-cisco** [cisco/acme-github-issue-tracking#17]
We use the checks API to create check suites for each PR.

On the pull request page, there's a checks tab, and a number is displayed next to the label "Checks" -- this number is always wrong, for every PR. It is always a multiple of the correct number.

Another issue which may or may not be related is that we sometimes see multiple instances of each check suite header on the checks tab.

The attached screenshots show both of these issues.  Please see the attachments in ticket 76463
In the first one, there's a PR with 4 commits, and the number is 4 times what it should be. But there's not always a correspondence like this. Even PRs with one commit have too many checks, as the second screenshot shows.

**Comment by isbadawi** [comment]
This one was already fixed in 2.15.
